language: dart
dist: xenial

addons:
  apt:
    packages:
    - lib32stdc++6
env:
  global:
    - ANDROID_SDK_ROOT=/opt/android
install:
- git clone https://github.com/flutter/flutter.git -b beta
- ./flutter/bin/flutter doctor

script:
# Setup gradle.
- wget https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
- unzip -qq gradle-4.10.3-bin.zip
- export GRADLE_HOME=`pwd`/gradle-4.10.3
- export PATH=$GRADLE_HOME/bin:$PATH
# (Quick fix: Silence sdkmanager warning)
- mkdir -p /home/travis/.android
- echo 'count=0' > /home/travis/.android/repositories.cfg

- yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;28.0.3" "extras;android;m2repository" > /dev/null
- export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH





- ls
#- export PATH="$PATH:`pwd`/flutter/bin"
#- cd buspay
#- ls
#- flutter build apk
#- ../flutter/bin/flutter test
cache:
  directories:
  - $HOME/.pub-cache
