


language: dart
language: android
dist: xenial
sudo: required



addons:
  apt:
    packages:
    - lib32stdc++6

android:
  components:
    - build-tools-26.0.2
    - android-26
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  global:
    - ANDROID_SDK_ROOT=/opt/android
install:
- git clone https://github.com/flutter/flutter.git -b beta
- ./flutter/bin/flutter doctor
- sudo apt-get install default-jdk

script:
# Setup gradle.
- wget https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
- unzip -qq gradle-4.10.3-bin.zip
- export GRADLE_HOME=`pwd`/gradle-4.10.3
- export PATH=$GRADLE_HOME/bin:$PATH

# Isso instalará o Android SDK 28 usando as ferramentas SDK instaladas anteriormente.
- yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;28.0.3" "extras;android;m2repository" > /dev/null
- export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH

- ls
- export PATH="$PATH:`pwd`/flutter/bin"
- flutter doctor -v
#- cd buspay
#- ls
#- flutter build apk
#- ../flutter/bin/flutter test
cache:
  directories:
  - $HOME/.pub-cache
