git:
  depth: 3

jobs:
  include:
    

    - name: "Android tests, stable channel"
      os: linux
      dist: trusty
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
      install:
	  - git clone https://github.com/flutter/flutter.git -b beta
          - ./flutter/bin/flutter doctor
      script: 
	  - ls

      env: FLUTTER_VERSION=stable

