


language: dart
language: android
dist: xenial




addons:
  apt:
    packages:
    - lib32stdc++6

android:
  components:
    - build-tools-26.0.2
    - android-26
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  global:
    - ANDROID_SDK_ROOT=/opt/android
install:
- git clone https://github.com/flutter/flutter.git -b beta
- ./flutter/bin/flutter doctor

script:
# Setup gradle.
- wget https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
- unzip -qq gradle-4.10.3-bin.zip
- export GRADLE_HOME=`pwd`/gradle-4.10.3
- export PATH=$GRADLE_HOME/bin:$PATH



- ls
#- export PATH="$PATH:`pwd`/flutter/bin"
#- cd buspay
#- ls
#- flutter build apk
#- ../flutter/bin/flutter test
cache:
  directories:
  - $HOME/.pub-cache
